engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.css"
  - "src/**.scss"
  - "src/**.js"
exclude_paths:
- test/
- tools/
- src/**/*spec.js
